### ISSUE TITLE
from(null) crashes simplystore

### ISSUE THREAD

**Issue by Hoxolotl** [SimplyEdit/SimplyStore#3]
entering "from(null)" in simplystore (localhost:3000/query/) crashes simplystore:

```
TypeError: arr.map is not a function
   at encodeEntries (file:///home/node/app/node_modules/@muze-nl/jsontag/src/lib/functions.mjs:55:29)
   at str (file:///home/node/app/node_modules/@muze-nl/jsontag/src/lib/functions.mjs:83:38)
    at JSONTag.stringify (file:///home/node/app/node_modules/@muze-nl/jsontag/src/lib/functions.mjs:142:9)
    at runQuery (file:///home/node/app/node_modules/@muze-nl/simplystore/src/worker-query.mjs:142:34)
  at /home/node/app/node_modules/piscina/dist/src/worker.js:141:32

Node.js v20.4.0
exited with code 1
```

**Comment by poef** [comment]
The current version no longer crashes, but does give a nasty error message on the console. 
The problem is in Jaqt. I've fixed this in version 0.10.3 by creating a special Null class with a toJSON function that returns null.
